name: Java CI with Maven

on:
  push:
    # 分支
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running go
    steps:
      - name: 在服务器上执行 sudo go run
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: | # 命令中的 & 表示在后台运行进程
            cd InkBook/InkBook_backend/
            sudo git checkout dev
            sudo git fetch --all 
            sudo git reset --hard origin/dev
            sudo git pull
            sudo fuser -k 8080/tcp
            sudo go run main.go &
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          args: "-tt"